#!/bin/bash

source /efs/deploy/.corebuild
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
. ./tested

jobstart "$$"
trap "jobtrace '$$'" 0 1 2 3 6
echo "our buildstate is $buildstage for $buildobj"
echo "in overlay network $overlay"

rm -rf /efs/media/jukebox/*

docker rmi registry:5000/${buildobj}:${buildstage} .
docker build -t registry:5000/${buildobj}:${buildstage} .
if [ $? -ne 0 ] ; then
exit
fi
docker push registry:5000/${buildobj}:${buildstage}
docker rmi registry:5000/${buildobj}:${buildstage}

fleetctl submit ${buildobj}@.service

sleep 5
fleetctl start ${buildobj}@heaven
sleep 8
fleetctl start ${buildobj}@hell
